// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AcquisitionSystem

#include "../ui.h"

void ui_ScreenRecording_screen_init(void)
{
ui_ScreenRecording = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenRecording, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Panel1 = lv_obj_create(ui_ScreenRecording);
lv_obj_set_width( ui_Panel1, 240);
lv_obj_set_height( ui_Panel1, 40);
lv_obj_set_x( ui_Panel1, 0 );
lv_obj_set_y( ui_Panel1, -100 );
lv_obj_set_align( ui_Panel1, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel1, LV_OBJ_FLAG_CLICKABLE | LV_OBJ_FLAG_PRESS_LOCK | LV_OBJ_FLAG_CLICK_FOCUSABLE | LV_OBJ_FLAG_GESTURE_BUBBLE | LV_OBJ_FLAG_SNAPPABLE | LV_OBJ_FLAG_SCROLLABLE | LV_OBJ_FLAG_SCROLL_ELASTIC | LV_OBJ_FLAG_SCROLL_MOMENTUM | LV_OBJ_FLAG_SCROLL_CHAIN );    /// Flags
lv_obj_set_scrollbar_mode(ui_Panel1, LV_SCROLLBAR_MODE_OFF);
lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0xD200AC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Panel1, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel1, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label5 = lv_label_create(ui_Panel1);
lv_obj_set_width( ui_Label5, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label5, LV_SIZE_CONTENT);   /// 1
lv_obj_set_x( ui_Label5, 26 );
lv_obj_set_y( ui_Label5, 0 );
lv_obj_set_align( ui_Label5, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label5,"  ");
lv_obj_set_style_text_font(ui_Label5, &ui_font_FontAwesome16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_ButtonCurrentTime = lv_btn_create(ui_Panel1);
lv_obj_set_width( ui_ButtonCurrentTime, 70);
lv_obj_set_height( ui_ButtonCurrentTime, 32);
lv_obj_set_x( ui_ButtonCurrentTime, -82 );
lv_obj_set_y( ui_ButtonCurrentTime, 0 );
lv_obj_set_align( ui_ButtonCurrentTime, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_ButtonCurrentTime, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_ButtonCurrentTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_ButtonCurrentTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_ButtonCurrentTime, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_ButtonCurrentTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_ButtonCurrentTime, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_color(ui_ButtonCurrentTime, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_text_opa(ui_ButtonCurrentTime, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_ButtonCurrentTime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_LabelCurrentTime = lv_label_create(ui_ButtonCurrentTime);
lv_obj_set_width( ui_LabelCurrentTime, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_LabelCurrentTime, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_LabelCurrentTime, LV_ALIGN_CENTER );
lv_label_set_text(ui_LabelCurrentTime,"00:00");
lv_obj_set_style_text_font(ui_LabelCurrentTime, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

}
