// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.3.2
// LVGL version: 8.3.6
// Project name: AcquisitionSystem

#include "../ui.h"

void ui_ScreenSetTime_screen_init(void)
{
ui_ScreenSetTime = lv_obj_create(NULL);
lv_obj_clear_flag( ui_ScreenSetTime, LV_OBJ_FLAG_SCROLLABLE );    /// Flags

ui_Button2 = lv_btn_create(ui_ScreenSetTime);
lv_obj_set_width( ui_Button2, 220);
lv_obj_set_height( ui_Button2, 45);
lv_obj_set_x( ui_Button2, 0 );
lv_obj_set_y( ui_Button2, 86 );
lv_obj_set_align( ui_Button2, LV_ALIGN_CENTER );
lv_obj_add_flag( ui_Button2, LV_OBJ_FLAG_SCROLL_ON_FOCUS );   /// Flags
lv_obj_clear_flag( ui_Button2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_bg_color(ui_Button2, lv_color_hex(0x292831), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Button2, lv_color_hex(0xD200AC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Button2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_width(ui_Button2, 2, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Button2, LV_BORDER_SIDE_FULL, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label7 = lv_label_create(ui_Button2);
lv_obj_set_width( ui_Label7, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label7, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label7, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label7,"Update");
lv_obj_set_style_text_font(ui_Label7, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel2 = lv_obj_create(ui_ScreenSetTime);
lv_obj_set_width( ui_Panel2, 240);
lv_obj_set_height( ui_Panel2, 40);
lv_obj_set_x( ui_Panel2, 0 );
lv_obj_set_y( ui_Panel2, -100 );
lv_obj_set_align( ui_Panel2, LV_ALIGN_CENTER );
lv_obj_clear_flag( ui_Panel2, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel2, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0xD200AC), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_side(ui_Panel2, LV_BORDER_SIDE_BOTTOM, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Label2 = lv_label_create(ui_Panel2);
lv_obj_set_width( ui_Label2, LV_SIZE_CONTENT);  /// 1
lv_obj_set_height( ui_Label2, LV_SIZE_CONTENT);   /// 1
lv_obj_set_align( ui_Label2, LV_ALIGN_CENTER );
lv_label_set_text(ui_Label2,"Set RTC Time");
lv_obj_set_style_text_font(ui_Label2, &lv_font_montserrat_16, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Panel3 = lv_obj_create(ui_ScreenSetTime);
lv_obj_set_width( ui_Panel3, 240);
lv_obj_set_height( ui_Panel3, 125);
lv_obj_set_x( ui_Panel3, 0 );
lv_obj_set_y( ui_Panel3, -9 );
lv_obj_set_align( ui_Panel3, LV_ALIGN_CENTER );
lv_obj_set_flex_flow(ui_Panel3,LV_FLEX_FLOW_ROW_WRAP);
lv_obj_set_flex_align(ui_Panel3, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
lv_obj_clear_flag( ui_Panel3, LV_OBJ_FLAG_SCROLLABLE );    /// Flags
lv_obj_set_style_radius(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_border_color(ui_Panel3, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT );
lv_obj_set_style_border_opa(ui_Panel3, 0, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_row(ui_Panel3, 15, LV_PART_MAIN| LV_STATE_DEFAULT);
lv_obj_set_style_pad_column(ui_Panel3, 10, LV_PART_MAIN| LV_STATE_DEFAULT);

ui_Roller1 = lv_roller_create(ui_Panel3);
lv_roller_set_options( ui_Roller1, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller1, 50);
lv_obj_set_height( ui_Roller1, 40);
lv_obj_set_x( ui_Roller1, -81 );
lv_obj_set_y( ui_Roller1, 11 );
lv_obj_set_align( ui_Roller1, LV_ALIGN_CENTER );

lv_obj_set_style_text_align(ui_Roller1, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller1, &lv_font_montserrat_16, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller1, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller1, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller2 = lv_roller_create(ui_Panel3);
lv_roller_set_options( ui_Roller2, "01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller2, 50);
lv_obj_set_height( ui_Roller2, 40);
lv_obj_set_x( ui_Roller2, -81 );
lv_obj_set_y( ui_Roller2, 11 );
lv_obj_set_align( ui_Roller2, LV_ALIGN_CENTER );

lv_obj_set_style_text_align(ui_Roller2, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller2, &lv_font_montserrat_16, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller2, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller2, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller3 = lv_roller_create(ui_Panel3);
lv_roller_set_options( ui_Roller3, "2023\n2024\n2025\n2026\n2027\n2028\n2029\n2030", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller3, 70);
lv_obj_set_height( ui_Roller3, 40);
lv_obj_set_x( ui_Roller3, -81 );
lv_obj_set_y( ui_Roller3, 11 );
lv_obj_set_align( ui_Roller3, LV_ALIGN_CENTER );

lv_obj_set_style_text_align(ui_Roller3, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller3, &lv_font_montserrat_16, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller3, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller3, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller4 = lv_roller_create(ui_Panel3);
lv_roller_set_options( ui_Roller4, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller4, 50);
lv_obj_set_height( ui_Roller4, 40);
lv_obj_set_x( ui_Roller4, -149 );
lv_obj_set_y( ui_Roller4, 126 );
lv_obj_set_align( ui_Roller4, LV_ALIGN_CENTER );

lv_obj_set_style_text_align(ui_Roller4, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller4, &lv_font_montserrat_16, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller4, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller4, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller5 = lv_roller_create(ui_Panel3);
lv_roller_set_options( ui_Roller5, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller5, 50);
lv_obj_set_height( ui_Roller5, 40);
lv_obj_set_x( ui_Roller5, -149 );
lv_obj_set_y( ui_Roller5, 126 );
lv_obj_set_align( ui_Roller5, LV_ALIGN_CENTER );

lv_obj_set_style_text_align(ui_Roller5, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller5, &lv_font_montserrat_16, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller5, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller5, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

ui_Roller6 = lv_roller_create(ui_Panel3);
lv_roller_set_options( ui_Roller6, "00\n01\n02\n03\n04\n05\n06\n07\n08\n09\n10\n11\n12\n13\n14\n15\n16\n17\n18\n19\n20\n21\n22\n23\n24\n25\n26\n27\n28\n29\n30\n31\n32\n33\n34\n35\n36\n37\n38\n39\n40\n41\n42\n43\n44\n45\n46\n47\n48\n49\n50\n51\n52\n53\n54\n55\n56\n57\n58\n59", LV_ROLLER_MODE_NORMAL );
lv_obj_set_width( ui_Roller6, 50);
lv_obj_set_height( ui_Roller6, 40);
lv_obj_set_x( ui_Roller6, -149 );
lv_obj_set_y( ui_Roller6, 126 );
lv_obj_set_align( ui_Roller6, LV_ALIGN_CENTER );

lv_obj_set_style_text_align(ui_Roller6, LV_TEXT_ALIGN_CENTER, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_text_font(ui_Roller6, &lv_font_montserrat_16, LV_PART_SELECTED| LV_STATE_DEFAULT);
lv_obj_set_style_bg_color(ui_Roller6, lv_color_hex(0x000000), LV_PART_SELECTED | LV_STATE_DEFAULT );
lv_obj_set_style_bg_opa(ui_Roller6, 0, LV_PART_SELECTED| LV_STATE_DEFAULT);

}
